### ISSUE TITLE
Morphological Segmentation crashes if stack too big?

### ISSUE THREAD

**Issue by Mathieu-Prouveur** [ijpb/MorphoLibJ#10]
Hello, 

I am currently using your plugin to label 2D videos of cells and depending on the computer I use, the morphological segmentation command may freeze Fiji.

For instance I tried to open this stack :  
![filteredimage](https://user-images.githubusercontent.com/24923813/29502543-6b8b9898-8663-11e7-9194-01ddddc27730.gif)

And here is what I get, when it crashes Fiji doesn't respond anymore and the morphological segmentation window is always blank with the 3200% tag : 
![crash](https://user-images.githubusercontent.com/24923813/29502525-47ce3136-8663-11e7-91ca-c8b722006fb5.PNG)

However if I take a substack, the plugin works perfectly fine and it also does if I pick an even better computer. 

So I guess it is related to the computer resources. But still I am surprised that it crashes for a 6Mo stack with 70 slices on a computer with 8*3.4GHz CPU,4*8GB RAM,4GB AMD Radeon HD7900 whereas it doesn't crash on a computer  with 20*3GHz CPU,64GB RAM, 4GB AMDFirePro W5100 even if i copy the stack 100 times so as to try the same command on a 7000 slices stack.

I would be very interested to have your opinion on the subject and to know if there is any solution other than sticking to the better computer. 

Thanks a lot for your work, so far the library is great anyway!

**Comment by iarganda** [comment]
Hello @Mathieu-Prouveur,
This is a [known issue](http://forum.imagej.net/t/blank-window-using-morphological-segmentation-morpholibj/6518) that has to do with the dimensions of your screen and the height and width of your input image being too small to zoom to 512x512 as required by the plugin GUI (so the GUI falls into an infinite loop of zooming). The bug has [been fixed](https://github.com/ijpb/MorphoLibJ/commit/00dca65d4c2e4791853d62fee6ee7c819cabc740), so just wait a bit for the next release (coming very soon!).

**Comment by Mathieu-Prouveur** [comment]
Great, thanks for the quick answer! I am still a bit puzzled by the fact that it worked fine with a substack though ^^' I'll wait for the next release then !
