### ISSUE TITLE
GeodesicDistanceMapPluginTest failing

### ISSUE THREAD

**Issue by imagejan** [ijpb/MorphoLibJ#14]
The [Travis CI builds](https://travis-ci.org/ijpb/MorphoLibJ) are currently failing due to a failing `GeodesicDistanceMapPluginTest`.

They were actually failing for quite some time already, but due to a bug in the `build.sh` script, the Travis build was reporting `SUCCESS` anyhow.

These are the lines reporting the failing test:
https://travis-ci.org/ijpb/MorphoLibJ/builds/320237372#L720-L722

Should the test be adjusted to match changes in the implementation? Or is the implementation faulty?

**Comment by iarganda** [comment]
Thank you very much, @imagejan I was wondering what was going on. @dlegland can you have a look?

**Comment by iarganda** [comment]
I found the problem. It was on a small change @dlegland made [28 days ago](https://github.com/ijpb/MorphoLibJ/commit/b4f1804a62ced86d25451b92d652da8f7b6c9d01#diff-dfc36f127957e8a5f6a03a3809dd3595).

**Comment by dlegland** [comment]
wow, very efficient! Thanks!

**Comment by dlegland** [comment]
Well, I realized that my test coverage was not complete. Good point to use Travis...
