### ISSUE TITLE
Imagecalculator bugged with 32 bits images

### ISSUE THREAD

**Issue by rfloresf** [ijpb/MorphoLibJ#15]
Hello,

The ImageCalculator.combineImages() gave me wrong results for 32bits images (works fine with 8 or 16 bits images), for ex. a null image if i multiply a 32bit image with itself.

Thank you for your help,
Rémy

**Comment by dlegland** [comment]
Hi Rémy,
yes, the class is currently performing computations using integer arithmetic. I will fix that!
David

**Comment by dlegland** [comment]
Hi Rémy,
I have updated the ImageCalculator class. It should provide correct result for floating point images.
Can you check it from the current master branch to see if you still have the problem ?

**Comment by rfloresf** [comment]
Hi David,
Thank you for the correction.
I'm not sure what the master branch is. I tried using these function for a groovy script instead of the imagej ones. Since i mostly write script that i distribute to my imaging facility users, i'll prefer to test the modification once the IJPB update site is updated.
Rémy

**Comment by imagejan** [comment]
@rfloresf the `master` branch is the latest state of this repository, where you submitted this issue. As this state is automatically built into a `SNAPSHOT` jar file by a service called Travis, and deployed to a central repository, you can download the `jar` file for testing from there:

http://maven.imagej.net/service/local/repositories/snapshots/content/fr/inra/ijpb/MorphoLibJ_/1.3.4-SNAPSHOT/MorphoLibJ_-1.3.4-20180312.103812-19.jar

I guess it would help if you can test the latest changes by downloading that file and replace your file `plugins/MorphoLibJ_-1.3.3.jar` with that newly downloaded file, to confirm that these changes actually fix your problem.

**Comment by dlegland** [comment]
@imagejan thanks for the information, I did not know latest snapshot was directly available via Travis! Good to know for future questions.
