### ISSUE TITLE
Issues while Saving Results from Morphological Segmentation

### ISSUE THREAD

**Issue by dtstone** [ijpb/MorphoLibJ#20]
1. PLUGIN EXPORTS ONLY 1 IMAGE REPEATEDLY: after finishing the segmentation and selecting the "basins" images, I would hit "create result" and save the basins image set. When I opened the basins image set later, the basins image set would just be 1 image repeated for the entire image set. 

2. PLUGIN EXPORTS MOST IMAGES, BUT CREATES DUPLICATES: similar to previous issue, I will export the basins image set and open the image set later to discover there was an issue that did not show up when viewing the images in the plugin. This time, nearly all images in the image set were exported properly but 1 or 2 images are actually duplicates of the previous image in the image set.

**Comment by iarganda** [comment]
Dear @dtstone 
I cannot reproduce this behavior, please make sure you are running on the latest version of Fiji and MorphoLibJ.

**Comment by dtstone** [comment]
I have confirmed that the issue with making duplicate images is a bug in FIJI itself and not this particular plugin.

**Comment by imagejan** [comment]
For others who follow: the issue is now tracked at https://github.com/fiji/fiji/issues/199.
