### ISSUE TITLE
MorpholibJ version

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#28]
Somehow I don't seem to get the latest features of MorpholibJ into my Fiji.
Are they maybe not yet pushed to the Update Site?
In other words: Is the information here correct?

https://imagej.net/MorphoLibJ

<img width="535" alt="image" src="https://user-images.githubusercontent.com/2157566/51206899-96fbdf80-1909-11e9-8ebf-e78d9b3bf7fd.png">

**Comment by iarganda** [comment]
My bad, I didn't do the Fiji release at the same time as our last release here. I'll do it right now.

**Comment by iarganda** [comment]
Done!

**Comment by dlegland** [comment]
Thanks Ignacio!
