### ISSUE TITLE
Max number of labels reached

### ISSUE THREAD

**Issue by thomasaarholt** [ijpb/MorphoLibJ#3]
Hello, and thank you for a very impressive plugin!
I'm running into an error when trying to segment an image of cracks:
```
Exception in thread "Thread-19" java.lang.RuntimeException: Max number of label reached (8388608)
```
I suspect it's because I'm running it on an edge dataset which has background noise in it. Would a common number of labels be much lower?

**Comment by iarganda** [comment]
Hello Thomas,

That error appears when you reach the maximum number of labels that you can properly stored in a 32-bit image. Do you really need so many labels or the problem can be solved by removing the noise?

**Comment by thomasaarholt** [comment]
You're quite right. I really don't need that many. I probably do need on the order of 5000, but yeah, 8 million was just noise :)
Cheers!
