### ISSUE TITLE
BoundingBox 

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#32]
@dlegland 

Dear David,

Could I somehow convince you to add the option for a bounding box to the 2D and 3D shape measurements?

* [X] BoundingBox
Maybe with naming scheme like this:
`BoundingBox.Min.X`
`BoundingBox.Min.Y`
`BoundingBox.Min.Z`
`BoundingBox.Max.X`
`BoundingBox.Max.Y`
`BoundingBox.Max.Z`

I assume that during the shape analysis you obtain those numbers anyway so it should be very cheap (or even for free) to add them. For me however it would be a **huge** benefit, because my downstream analysis would know where in 3D space the segmented objects are living (and this information is quite expensive to get, because one almost has to run a connected component analysis again).

**Comment by dlegland** [comment]
Hi,
yes, that should be possible!
I try to have a look during next weeek.
best!

**Comment by dlegland** [comment]
Hi,
I just commited a version that includes computation of boundingbox into analyze regions 3D plugin.
I just chose a different ordering of parameters: 

    Box.X.Min
    Box.X.Max
    Box.Y.Min
    Box.Y.Max
    Box.Z.Min
    Box.Z.Max

But I think this fits the request?

best,
David

**Comment by dlegland** [comment]
(in commit e198ae0534d0043bbd946976336488c2302e45fe )

**Comment by tischi** [comment]
Looks fantastic! 
Is that already in Fiji?

**Comment by dlegland** [comment]
I don't think so... it should be when we'll release next version I guess.

**Comment by dlegland** [comment]
Hi,
new version (1.4.1) of MorphoLibJ was released recently, I suppose it should be available within Fiji soon.

Best,
David
