### ISSUE TITLE
Wrong window title

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#35]
Hello,

When running "Analyze Regions'" the window title is "Particle Analysis 3D":

![image](https://user-images.githubusercontent.com/2157566/74420362-9951a580-4e4b-11ea-8ace-774552659d9a.png)

Probably should be changed. Thank you.

**Comment by iarganda** [comment]
Hey @tischi That issue is fixed here: https://github.com/ijpb/MorphoLibJ/commit/408e861668f02c27d2fbc7936102cdabef0995a5

We just need to make a new release ;-)
