### ISSUE TITLE
Bug in Intensity Measure

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#36]
There seems to be a bug in the Intensity Measure command:

![image](https://user-images.githubusercontent.com/2157566/74422568-1af70280-4e4f-11ea-9da1-9f8b28c40122.png)

![image](https://user-images.githubusercontent.com/2157566/74422617-2c400f00-4e4f-11ea-9e9f-52234de4a79b.png)

**Comment by iarganda** [comment]
Hey @tischi ! I believe this is fixed now thanks to @dlegland who work on this in a [parallel issue](https://github.com/ijpb/MorphoLibJ/issues/38#issuecomment-601311192).

**Comment by dlegland** [comment]
yes, and next time I open an issue, I will first check it does not alread exists...
