### ISSUE TITLE
Bug in Classic Watershed?

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#37]
Hello,

When we put an image as a "Mask" that is not binary to "Classic Watershed", it still does something (which we do not understand). Should it work or should it maybe better throw and error if the Mask image is not binary?

**Comment by iarganda** [comment]
It should probably throw an error, indeed ;-)

**Comment by iarganda** [comment]
[This commit](https://github.com/ijpb/MorphoLibJ/commit/d4635ed83e4ed568c3451ec057d3cf461fd285a9) should fix it!
