### ISSUE TITLE
Bug in Intensity Measure 2D/3D - Max value in 32bit images

### ISSUE THREAD

**Issue by ofrag** [ijpb/MorphoLibJ#44]
Hi,

When I run Intensity Measure 2D/3D on 32 bit image that has negative values (output of FeatureJ Laplacian) with corresponding label image. The Max value is not calculated correctly for cases in which the Max is negative. a low value 4.900e-324 is given instead.  

Thanks
Ofra

**Comment by dlegland** [comment]
Hi,
thanks for reporting! I think this may be due to a wrong initialization of the max value. I will check it!

David

**Comment by dlegland** [comment]
Hi,
I had a look and could make a fix (this was indeed the initialization...).
If you're in hurry you can get the fix by cloning/updating the source. Anyway it will be time for a new release soon....

**Comment by ofrag** [comment]
Thanks David

For my case, I inverted the image and used the minimum.
MorphoLibJ is one of my favorites and most useful plugin.
Thanks for developing and sharing.

Ofra
