### ISSUE TITLE
Image names ending with .tif

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#48]
@dlegland 
I have an issue macro recording the analysis of images whose name ends with .tif
Could it be that you are somehow removing the ending when presenting the choices for which images to select?

**Comment by dlegland** [comment]
Hi,
yes maybe. 
The default behaviour in most MLJ plugins is to use the "short name" of the images, and to add a suffix like "-crop", "-filter"...

maybe a rename command in the beginning of the macro could solve the pbm?

**Comment by tischi** [comment]
> maybe a rename command in the beginning of the macro could solve the pbm?

Yes, it does. Not sure whether this is good though. I think beginners would have zero chance of figuring this out.

**Comment by dlegland** [comment]
Hmm, not clear to me... When a new image is created, a new name is generated. So the problem is to get image name from the input image name and assuming the processing within plugin, right? The processing will always being plugin-dependent IMHO...

**Comment by tischi** [comment]
I am fetching the name of the current image, using `getTitle()`:

```
input = getTitle();
run("Intensity Measurements 2D/3D", "input=["+input+"] labels=mask mean numberofvoxels");
```
But if `input.contains(".tif")` it crashes.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2157566/107938169-3d9d8900-6f85-11eb-9626-9487b0777e22.png">

**Comment by dlegland** [comment]
OK, so it seems this is a bug....
I try to have a look. I also cc @iarganda , I think he wrote the plugin originally

**Comment by dlegland** [comment]
well, I think I found!
just need to recompile (i.e., fighting with maven), to get a new version...

**Comment by dlegland** [comment]
You can try new snapshot version:
https://github.com/ijpb/MorphoLibJ/releases/tag/v1.4.3-test

**Comment by tischi** [comment]
Thanks! I trust you :)
