### ISSUE TITLE
Nonsensical while loop (h < hMin), while h is already set to hMin

### ISSUE THREAD

**Issue by dmikushin** [ijpb/MorphoLibJ#5]
This report concerns specifically `applyWithMask` function of `WatershedTransform2D.java`, but may also be similar for other locations/transforms.

Here h is already set to hMin: https://github.com/ijpb/MorphoLibJ/blob/master/src/main/java/inra/ijpb/watershed/WatershedTransform2D.java#L283

However, the following while loop checks for (h < hMin), and hence will never be entered:
```
        // find corresponding pixel index
        int currentIndex = 0;
        while( h < hMin )
        {
        	h = pixelList.get( currentIndex ).getValue();
        	currentIndex++;
        }
```

Perhaps, there should be:

```
// initial height
double h = 0;

int currentIndex = 0;
for ( ; currentIndex < pixelList.size(); currentIndex++)
{
    h = pixelList[currentIndex];
    if (h >= hMin) break;
}
```

?

**Comment by iarganda** [comment]
You are right, that code there was useless. I have just removed it in both the 2D and 3D version. Fortunately, it didn't affect the method at all.

**Comment by dmikushin** [comment]
Yes, `extractPixelValues` already takes care of everything by giving us only pixels in [hMin, hMax] range. Thus, the check for h <= hMax could also be dropped in the while loop condition. Then, "h" could be initialized in the body of while loop. Please see #6
