### ISSUE TITLE
Feature request total number of pixels in 3D label analyze

### ISSUE THREAD

**Issue by manerotoni** [ijpb/MorphoLibJ#50]
Hello,
I wonder if in `Analyze > Analyze Regions 3D` and `Analyze Regions` you could add the number of pixels of the objects (without scaling).

The reason is that to find the size to filter objects it requires values in pixel units, and this is not easy to get when the size is given in physical volume.  

Thanks

Antonio

**Comment by dlegland** [comment]
Hi Antonio, 
yes, this is a good idea. 
One solution could be to clear the spatial calibration before running measurement, but this makes it tedious to switch from calibrated / uncalibrated data. I'll work on it!
David

**Comment by dlegland** [comment]
Hi,
I implemented it in https://github.com/ijpb/MorphoLibJ/commit/2844b25389afe6f74791b57ae15ae53d6e6fbf2b
There is also the equivalent feature for 2D region analysis.

**Comment by manerotoni** [comment]
Great thanks! I guess you will update the version on the repo in the near future.

**Comment by dlegland** [comment]
yes, I plan to make a release soon! Hopefully this month.
