### ISSUE TITLE
Question About Reconstructing images from the IMAGE J results file

### ISSUE THREAD

**Issue by AhanaMallick** [ijpb/MorphoLibJ#56]
Hi!!

Is it possible to reconstruct the 3-D analysis regions from the results table in image j?

Ahana.

**Comment by dlegland** [comment]
Hi,
sorry, I did not fully understand the question... what do you mean by "reconstruct", and which tables do you refer to?

**Comment by AhanaMallick** [comment]
I am using a segmentation editor to select ROIs and then using the MorphoLibj plugin to analyze the volume of the ROIs. My question is can I use the values from the resultant Results Table  after Region Analysis (this is a 3D image), to reconstruct the ROIs?

**Comment by dlegland** [comment]
Hi,
no, it is not possible to reconstruct a ROI from a set of measurements on the images.
Best,
David

**Comment by AhanaMallick** [comment]
Okay thank you!

Ahana.
