### ISSUE TITLE
Label edit does not show the final labeled image

### ISSUE THREAD

**Issue by manerotoni** [ijpb/MorphoLibJ#57]
Hello,
the label Edition command does not display the image after one press done. 
strangely enough the image is shown in the Window list but does not display.

Greetings

Antonio

**Comment by iarganda** [comment]
Dear @manerotoni,

Can you please provide more information about your installation:
Windows, Linux or Mac?
ImageJ or Fiji?

I'm not able to reproduce the error.

**Comment by manerotoni** [comment]
Hello @iarganda,
I tried now with an updated version of fiji and it does work. I think you can delete my comment.
It may have been a fiji glitch for a short time.
Antonio
