### ISSUE TITLE
Gray Scale Attribute Filtering 3D not working

### ISSUE THREAD

**Issue by ClemenceKress** [ijpb/MorphoLibJ#59]
Hello,

I used Gray Scale Attribute Filtering on 2D image without problem in Fiji (everything updated). I'd like to do the same on 3D images now.
But when I try to use Gray Scale Attribute Filtering 3D on a stack, I get the following message:

(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_202 [64-bit]; Mac OS X 10.16; 44MB of 8004MB (<1%)
 
java.lang.RuntimeException: Unknown connectivity: 4
	at inra.ijpb.morphology.attrfilt.SizeOpening3DQueue.process(SizeOpening3DQueue.java:99)
	at inra.ijpb.morphology.AttributeFiltering.volumeOpening(AttributeFiltering.java:131)
	at inra.ijpb.plugins.GrayscaleAttributeFiltering3D.run(GrayscaleAttributeFiltering3D.java:202)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

I get the same results if I change the connectivity value. Could you help me?
Thank you

**Comment by dlegland** [comment]
There is no official date for the next "big" release; we are currently working on several changes, so a new release could be available "soon"...
In the meanwhile, I have released a bug-fix release; you can download it here:
https://github.com/ijpb/MorphoLibJ/releases/tag/v1.4.3.1

(simply download the jar, and use it as replacement of previous MorphoLibJ jar in the ."../Fiji.app/plugins" directory)

**Comment by ClemenceKress** [comment]
Thank you, indeed it works now.
Your plugin is great. the distance transform watershed is very efficient for the segmentation of nuclei of various shape and intensity within tissue sections. And the possibilities for label edition are very handy: with merging and manual correction of shapes I manage to obtain a correct segmentation for all nuclei, which is quite remarkable. 
I also appreciate a lot the documentation about the plugin, it is very clear to understand what the tools do. This is really not the case with some other plugins (I'm currently struggling with other ones for 3D analysis).
