### ISSUE TITLE
Fill holes in labels

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#67]
@dlegland 

For one of our projects it would be very useful to have a "Fill holes in labels" option.
Would that be within scope to add?

**Comment by dlegland** [comment]
Hi,
yes, could be a good idea, but there would be problems when some labels are enclosed into other labels... What behaviour would you expect in that case?

**Comment by tischi** [comment]
Hm, I guess I would expect that the outer label is filled until it hits the inner label, thus not changing the inner label. Essentially, I would say that the algorithm only is allowed to change the values of background (`0`) pixels.

**Comment by dlegland** [comment]
yes, sounds logical. However I am not sure this is that easy to implement (not straightforward to differentiate inner hole to non-inner background...).

**Comment by dlegland** [comment]
Implemented in a664ec191008bce8b4c1a0610110be6bff8961b6,
and released within MorphoLibJ 1.6.0.
