### ISSUE TITLE
Erode labels

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#68]
@dlegland Would it be possible to add an `Erode Labels` function?

**Comment by dlegland** [comment]
looks possible yes!
I will have a look when possible.

**Comment by dlegland** [comment]
Implemented in pre-version https://github.com/ijpb/MorphoLibJ/releases/tag/v1.5.1-LabelMorphologicalFilters ;

**Comment by dlegland** [comment]
- [ ] Add static functions for erosion/dilation... in inra.ijpb.label.LabelImages class.

**Comment by dlegland** [comment]
now implemented!
