### ISSUE TITLE
closing close to image boundary

### ISSUE THREAD

**Issue by tischi** [ijpb/MorphoLibJ#73]
@dlegland 

please see here: https://forum.image.sc/t/morphological-closing-close-to-image-boundaries/74543

**Comment by tischi** [comment]
Could not upload images, posting on forum instead.

**Comment by dlegland** [comment]
Hi,

the behaviour is to replicate pixels values when close to border. Thius was chosen to avoid "shrinking" regions that touch the border.

I think other conventions could be used as well, but i am not sure a universal one is possible...

A quick workaround is to pad image with a brder. There is a plugin "Add Border" in MLJ.

hope this helps?

**Comment by dlegland** [comment]
fixed in MorphoLibJ 1.6.0 (commit [295e8946f5ccb4d5bedc38b210cd90d6771e2cfa](https://github.com/ijpb/MorphoLibJ/commit/295e8946f5ccb4d5bedc38b210cd90d6771e2cfa)
