### ISSUE TITLE
Typo in MorphologicalSegmentation.java

### ISSUE THREAD

**Issue by lldelisle** [ijpb/MorphoLibJ#81]
Dear developers,
I think I found a bad copy paste in MorphologicalSegmentation.java:
https://github.com/ijpb/MorphoLibJ/blob/b20843b529917cd7a99ea71be24bf1ab3efcab23/src/main/java/inra/ijpb/plugins/MorphologicalSegmentation.java#L1115-L1119
I guess it should be `Morphology.externalGradient` the second time.

**Comment by dlegland** [comment]
Hi!
thanks for reporting; seems like a bad copy-paste, indeed!
I have just fixed it (commit 4b702142a9253618e90b09e457d63f6b893e98e1)
Best!
